config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'pages/about'
  resources :users
  resources :articles
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_one_attached :main_image

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/article_category.rb
# frozen_string_literal: true

class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_one_attached :avatar
  before_save { self.email = email.downcase }

  validates :fullname, presence: true,
                       uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :mobile_no, uniqueness: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[fullname mobile_no avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[fullname mobile_no avatar])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article '#{@article.title}' was created!"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = "Article '#{@article.title}' was successfully updated!"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article '#{@article.title}' was successfully deleted!"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id, category_ids: [])
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 2)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = 'Category was created successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all  
  end

  def show
    @user = User.includes(:articles).find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:fullname, :mobile_no, :avatar)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
    def display_avatar(user)
        if user.avatar.attached?
          cloudinary_url(user.avatar.key)
        else
          asset_path('avatar.png')
        end
      end
end

app/views/articles/_form.html.erb
<%if @article.errors.any?%>
  <ul>
	<% @article.errors.full_messages.each do |msg|%>
	  <li><%= msg %></li>
	<%end%>
  </ul>
<%end%>

<%= form_for @article do |f| %>


  <p class="mr-3">
    <%= f.label :categories1 %><br />
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "mr-3") {cb.check_box(class: "mr-3") + cb.text} %>
    <% end %>
	</p>

  <p>
    <%= f.label :categories2 %><br />
    <% for category in Category.all %>
      <%= check_box_tag "article[category_ids][]", category.id, @article.categories.include?(category) %>
      <%= category.name %><br />
    <% end %>
  </p>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing an Article</h1>

<%= render 'form' %><br />

<p><%= link_to 'Cancel', article_path %></p>

app/views/articles/index.html.erb
<div>
  <p><%= will_paginate @articles %></p><br />
  <% @articles.each do |article| %>
    <div>
      <h3><%=link_to article.title, article_path(article) %></h3>
      <p><%= truncate(article.description, length: 100) %></p>
      <p>Author: <strong> <%= article.user.fullname %></strong></p>
      <p class="text-muted"><small>Added: <%= time_ago_in_words(article.created_at) %> ago,
	                           Last updated: <%= time_ago_in_words(article.updated_at) %> ago</small></p>
      <% if article.categories.any? %>
      <p>Categories:
	    	<% article.categories.each do |categories| %>
	      	<span class=""> <%= categories.name %> </span>	
	    	<% end %>
	    <% end %>
         
          <% if current_user.id == article.user.id %>
              <p><%= link_to 'Edit', edit_article_path(article) %> ||
                <%= link_to 'Delete', article_path(article), method: :delete, date: { confirm: 'Are you sure?' } %></p>
          <% end %>
    </div>
    
  <% end %>

</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %><br />

<%= link_to 'Back to Articles', articles_path %>

app/views/articles/show.html.erb
<h1>Title - <%= @article.title %></h1>
<p><%= @article.description %></p>
<p>Author: <%= @article.user.fullname %></p>

<% if @article.categories.any? %>
  <p>Categories:
		<% @article.categories.map(&:name).each do |name| %>
    <%= "#{name} | " %>
  <% end %>
<% end %>
</p>

<p><%= link_to 'Edit', edit_article_path %>
  || <%= link_to 'Delete', article_path, method: :delete, date: { confirm: 'Are you sure?' } %>
</p>


<%= link_to '<<< All Articles', articles_path %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
<div  class="center  ">
<p><%= link_to 'New Category?', new_category_path %></p>
	<% @categories.each do |category| %>
	<ul class="list">
		<div class="row">
			<div class=" col-md-4 ">
				<li class="card-title">
					<%= link_to "#{category.name}", category_path(category) %>
				    <small><%= pluralize(category.articles.count, "article") %></small>
               </li>
				
			</div>
		</div>
	</ul>
	<% end %>
	<div class="row list">
		<div class="offset-5">
			<li class="card-title">
		      <%= will_paginate %>
			</li>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'shared/errors', obj: @category %>
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :name %>
	</div>
	<div class="col-sm-8">
		<%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="offset-2 col-sm-10">
		<%= f.submit class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>
<div class="col-xs-4 offset-4">
	[ <%= link_to "Cancel and back to the Articles List", articles_path %> ]
</div> 

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<div align="center">
	<%= will_paginate @category_articles %>
</div>

<% @category_articles.each do |c_a| %>
  <p><%= c_a.id %>. <%= c_a.title %></p>
<% end %>
<div align="center">
	<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-5 py-2 bg-light fixed-bottom">
  <div class="container text-muted">
	<small>
	  Copyright &copy <a href="https://www.linkedin.com/in/oksana-petrova/"></a> Laguna1 by
		<a href="https://www.linkedin.com/in/oksana-petrova/">Oksana Petrova</a>
	</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light  bg-primary text-white">
  <%= link_to "A-Bloger", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to  "All Articles",  articles_path, class: "nav-link text-light"  %>
      </li>
      <li><%= link_to 'New Article?', new_article_path, class: "btn btn-primary nav-link px-2 text-white" %></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><%= link_to 'Home', root_path, class: "nav-link px-2 text-white" %></li>
      <li class="nav-item active">
        <%= link_to  "About",  pages_about_path, class: "nav-link text-light"  %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item dropdown text-light">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Article
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to  "Create",  new_article_path, class: "nav-link text-dark"  %>
          <%= link_to  "Edit",  new_article_path, class: "nav-link text-dark"  %>
          <%= link_to  "Delete",  new_article_path, class: "nav-link text-dark"  %>
        </div>
      </li>
      <!-- Categories -->
      <li class="nav-item dropdown text-light">
        <a href="#" class="nav-link dropdown-toggle text-light" data-toggle="dropdown" role="button" aria-haspopup="true"
          aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Categories", categories_path, class: "nav-link text-dark" %></li>
          <% Category.all.each do |category| %>
          <li><%= link_to "#{category.name}", category_path(category), class: "nav-link text-dark"%></li>
          <% end %>
          
        </ul>
      </li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="nav-item dropdown text-light">
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to  "Edit your profile", edit_user_registration_path, class: "nav-link text-dark"  %>
        </div>
      </li>
      <li><%= link_to 'Log out', destroy_user_session_path, class: "nav-link text-light", method: :delete %></li>
      

      <% else %>
      <li><%= link_to 'Log in', new_user_session_path, class: "nav-link text-light" %></li>
      <li><%= link_to 'Sign up', new_user_registration_path, class: "nav-link text-light" %></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg%></li>
  </ul>
<%end%>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
	<%= link_to "A-Blogger", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li>
            <%= link_to  "Blog",  articles_path, class: "nav-link text-light"  %>
        </li>
      <li class="nav-item active">
		<%= link_to  "About", "#", class: "nav-link text-light"  %>
	  </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to  "Add new Article",  new_article_path, class: "nav-link text-dark"  %>
        <%= link_to  "Edit",  "#", class: "nav-link text-dark"  %>
        <%= link_to  "Delete",  "#", class: "nav-link text-dark"  %>
    </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABlogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <div class="container-fluid  h-100">
    <%= render 'layouts/header' %>
    <%= render 'layouts/msg' %>
      
        
      
    
    
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/header2.html.erb
<header class="p-3 bg-primary text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li class="nav-item dropdown text-light">
        <a href="#" class="nav-link dropdown-toggle text-light" data-toggle="dropdown" role="button" aria-haspopup="true"
          aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Categories", categories_path, class: "nav-link text-dark" %></li>
          <% Category.all.each do |category| %>
          <li><%= link_to "#{category.name}", category_path(category), class: "nav-link text-dark"%></li>
          <% end %>
        </ul>
      </li>
          <li><%= link_to 'Categories', categories_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to 'Articles', articles_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to 'New Article?', new_article_path, class: "btn btn-primary nav-link px-2 text-white" %></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><%= link_to 'Home', root_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to 'About', pages_about_path, class: "nav-link px-2 text-white" %></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="d-flex">
          <div class="row">
          <p>
          <% if user_signed_in? %>
            Welcome <strong><%= current_user.fullname %></strong>!
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link px-2 text-white"  %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link px-2 text-white" %>
            
          
          <% else %>
          
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link px-2 text-white'  %> |
            <%= link_to "Login", new_user_session_path, class: 'nav-link px-2 text-white'  %>
          <% end %>
          </p>
          <%# <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button> %>
          </div>
        </div>
      </div>
    </div>
  </header>

app/views/pages/about.html.erb
<div class="container py-4">
  <h4 class="text-center mt-2">Pages#about</h4>
    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold text-center pb-3">A-Blog</h1>
        <p class="col-md-12 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
		                         Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
		</p>
        <%= link_to "Sign up", "#", class: 'btn btn-primary btn-lg ' %>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<main>
  <h4 class="py-5 text-center">Pages#home</h4>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="display-5 fw-bold text-center pb-3">Blog Example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
           <%= link_to 'About Page', pages_about_path, class: "btn btn-primary my-2" %>
          
          <%= link_to 'All Articles', articles_path, class: "btn btn-success my-2" %></p>
        </p>
      </div>
    </div>
  </section>
</main>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row m-3">
  <div class="col-xs-8 offset-md-2">
	<div class="card bg-info">
	  <div class="card-body">
		<h2 class="card-title">
		  <%= pluralize(obj.errors.count, "error") %>
			 Prohibited this article from being saved:
		</h2>
	  <div class="card-body">
	    <ul>
		  <% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		</ul>
	  </div>
	  </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1>users#index</h1>
<% @users.each do |user| %>
  
  <p><%= link_to user.fullname, user_path(user) %></p>
  <p>Articles: <%= user.articles.count %></p>
  <p>*****************************</p>
  <% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<div class="w-50" style="background-image: url(<%= display_avatar(@user) %>)"></div>
<%= user_avatar(@user) if @current_user == @user %>
<p><%= @user.fullname %></p>
<p>Articles: <%= @user.articles.count %></p>